[project]
name = "receipt-service"
version = "0.1.0"
description = ""
authors = [
    {name = "maxonclaxon",email = "satamaks@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pika (>=1.3.2,<2.0.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "pydantic-settings (>=2.7.1,<3.0.0)",
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    "numpy (>=2.2.2,<3.0.0)",
    "pillow (>=11.1.0,<12.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
package-mode = false

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"


[[tool.poetry.source]]
name = "foo"
url = "https://pypi.org/simple"
priority = "supplemental"

