name: Receipt Service Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test

env:
  DOTENV_FILENAME: /tmp/receipt-service.env
  DOCKERHUB_SERVICE_NAME: gobigagency/receipt-service
  DOCKER_SERVICE_NAME: receipt-service

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to hub
        run: |
          docker build -t ${{ env.DOCKERHUB_SERVICE_NAME }}:latest .
          docker push ${{ env.DOCKERHUB_SERVICE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            touch ${{ env.DOTENV_FILENAME}}
            echo RABBITMQ_HOST=${{ vars.RABBITMQ_HOST }} >> ${{ env.DOTENV_FILENAME}}
            echo LOGGING_LEVEL=${{ vars.LOGGING_LEVEL }} >> ${{ env.DOTENV_FILENAME}}
            echo SERVICE_EMAIL_ADDRESS=${{ vars.SERVICE_EMAIL_ADDRESS }} >> ${{ env.DOTENV_FILENAME}}
            echo EMAIL_SMTP_ADDRESS=${{ vars.EMAIL_SMTP_ADDRESS }} >> ${{ env.DOTENV_FILENAME}}
            echo EMAIL_SMTP_PORT=${{ vars.EMAIL_SMTP_PORT }} >> ${{ env.DOTENV_FILENAME}}
            echo FTP_HOST=${{ vars.FTP_HOST }} >> ${{ env.DOTENV_FILENAME}}
            echo FTP_USERNAME=${{ vars.FTP_USERNAME }} >> ${{ env.DOTENV_FILENAME}}
            echo FTP_PASSWORD=${{ secrets.FTP_PASSWORD }} >> ${{ env.DOTENV_FILENAME}}
            echo EMAIL_TOKEN=${{ secrets.EMAIL_TOKEN }} >> ${{ env.DOTENV_FILENAME}}
            echo RECEIPTS_RABBIT_QUEUE=${{ vars.RECEIPTS_RABBIT_QUEUE }} >> ${{ env.DOTENV_FILENAME}}     
      
      - name: Deploy Receipt Service Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ env.DOCKERHUB_SERVICE_NAME }}:latest

            docker stop ${{ env.DOCKER_SERVICE_NAME }} || true
            docker rm ${{ env.DOCKER_SERVICE_NAME }} || true

            docker network inspect ${{ vars.SERVICE_DOCKER_NETWORK }} >/dev/null 2>&1 || \
            docker network create --driver bridge ${{ vars.SERVICE_DOCKER_NETWORK }}

            docker run -d \
              --name ${{ env.DOCKER_SERVICE_NAME }} \
              --restart always \
              --network ${{ vars.SERVICE_DOCKER_NETWORK }} \
              --env-file ${{ env.DOTENV_FILENAME }} \
              ${{ env.DOCKERHUB_SERVICE_NAME }}:latest
      
      - name: Delete .env file
        uses: appleboy/ssh-action@master
        if: always()
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -f ${{ env.DOTENV_FILENAME}}