name: Receipt Service Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test

env:
  DOTENV_FILENAME: /tmp/receipt_service.env

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to hub
        run: |
          docker build -t gobigagency/receipt-service:latest .
          docker push gobigagency/receipt-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            touch ${{ env.DOTENV_FILENAME}}
            echo RABBITMQ_HOST=${{ vars.RABBITMQ_HOST }} >> ${{ env.DOTENV_FILENAME}}
            echo LOGGING_LEVEL=${{ vars.LOGGING_LEVEL }} >> ${{ env.DOTENV_FILENAME}}
            echo EMAIL_SMTP_ADDRESS=${{ vars.EMAIL_SMTP_ADDRESS }} >> ${{ env.DOTENV_FILENAME}}
            echo EMAIL_SMTP_PORT=${{ vars.EMAIL_SMTP_PORT }} >> ${{ env.DOTENV_FILENAME}}
            echo FTP_HOST=${{ vars.FTP_HOST }} >> ${{ env.DOTENV_FILENAME}}
            echo FTP_USERNAME=${{ vars.FTP_USERNAME }} >> ${{ env.DOTENV_FILENAME}}
            echo FTP_PASSWORD=${{ secrets.FTP_PASSWORD }} >> ${{ env.DOTENV_FILENAME}}
            echo EMAIL_TOKEN=${{ secrets.EMAIL_TOKEN }} >> ${{ env.DOTENV_FILENAME}}
            
      - name: Deploy Receipt Service Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull gobigagency/receipt-service:latest

            docker stop receipt_service || true
            docker rm receipt_service || true

            docker network inspect ${{ vars.SERVICE_DOCKER_NETWORK }} >/dev/null 2>&1 || \
            docker network create --driver bridge ${{ vars.SERVICE_DOCKER_NETWORK }}


            docker run -d \
              --name receipt_service \
              --restart always \
              --network ${{ vars.SERVICE_DOCKER_NETWORK }} \
              --env-file ${{ env.DOTENV_FILENAME }}
              gobigagency/receipt-service:latest
      
      - name: Delete .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm ${{ env.DOTENV_FILENAME}}